### ISSUE TITLE
Avoid Using !!(null check)

### ISSUE THREAD

**Issue by logicgupta** [ByteMonk-GCECT/GCECT-APP#10]
- We should avoid using **!!** checks , instead we should wrap inside a let keyword . I have seen any apps that lead to crashes because to this issue .  I would like to replace this to good practice to check null . Please assign me

**Comment by HeySitam** [comment]
Yeah sure go ahead. Also you can use elvis operator too. if possible make some comments also there to increase the readbility.

**Comment by logicgupta** [comment]
completed :) pls check my PR

**Comment by chayan-dev** [comment]
issue merged 👍
