### ISSUE TITLE
History and The Institute Fragment

### ISSUE THREAD

**Issue by shounak-dev** [ByteMonk-GCECT/GCECT-APP#12]
### Contact Details

shounakdas30@gmail.com

### GSSoC-22

yes

### Type of Issue

UI Related

### Description

Ui implementation of History and The Institute fragment.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shounak-dev** [comment]
I want to work on this issue, can someone tell me about what is the ui for this fragment?

**Comment by chayan-dev** [comment]
try to make the UI responsive not static. If you need any help feel free to ask

**Comment by chayan-dev** [comment]
![image](https://user-images.githubusercontent.com/50614321/156344311-c766c57a-80ee-4060-9dec-9e926c1eb29a.png)

copy the text shown in history fragment from (http://gcect.ac.in/history/)
and for the institute from (http://gcect.ac.in/about-us/)

**Comment by chayan-dev** [comment]
I have also sent an invite for the figma file. confirm whether you are able to acces it or not

**Comment by shounak-dev** [comment]
Yes....I am able to access it.
