### ISSUE TITLE
Consultancy fragment implementation

### ISSUE THREAD

**Issue by chayan-dev** [ByteMonk-GCECT/GCECT-APP#14]
UI implementation of consultancy fragment. try to make the UI responsive.
UI design for the fragment:
![image](https://user-images.githubusercontent.com/50614321/156349555-54f55be7-a652-43cd-bcec-825c5bd8191a.png)

for all the text shown in the fragment, you can copy from(http://gcect.ac.in/consultancy/)

**Comment by sdcode001** [comment]
@chayan-dev I want to work on this issue. please assign it to me

**Comment by AgarwalsRahul** [comment]
@chayan-dev I would like to work on this issue. please assign it to me.

**Comment by maityamit** [comment]
Me : Amit Maity
**GSSoC'22** - Yes 

@chayan-dev I would like to work this issue . 
Please assign me.

**Comment by ConnectBhawna** [comment]
Bhawna 
GSSOC'22 - yes

@chayan-dev could you please assign it to me
