### ISSUE TITLE
UI improvement of side navigation bar

### ISSUE THREAD

**Issue by Yash-Parsana** [ByteMonk-GCECT/GCECT-APP#15]
### Contact Details

yashcode2003@gmai.com

### GSSoC-22

yes

### Type of Issue

UI Related

### Description

i want to improve UI of side navigation bar 
changes that i want to do
circular gcect logo
non transparent background
changes in some logo
reduce radius of background
remove line after all items

BEFORE

![WhatsApp Image 2022-03-02 at 5 23 30 PM](https://user-images.githubusercontent.com/77839976/156362733-2526ca5a-4a63-4a5f-94f7-9d31320fbcf1.jpeg)

AFTER

![untitled (3)](https://user-images.githubusercontent.com/77839976/156362812-5482cb69-da8a-463b-95c5-0ca18766a5bc.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Yash-Parsana** [comment]
I want to work on it under Gssoc22

**Comment by AgarwalsRahul** [comment]
I would like to work on this issue. Please assign this issue to me

**Comment by HeySitam** [comment]
hey @Yash-Parsana your theme is really great. but actually we want the bluish color combination. Would you please continue with blueish theme? remaining design is pretty cool.

**Comment by Yash-Parsana** [comment]
> hey @Yash-Parsana your theme is really great. but actually we want the bluish color combination. Would you please continue with blueish theme? remaining design is pretty cool.

@sitamadex11 
Yes I will do it with same color which is present in original navigation bar.

May I go further ?

**Comment by HeySitam** [comment]
yeah sure. Also will be better if you share a recorded video before your PR.

**Comment by Yash-Parsana** [comment]
> yeah sure. Also will be better if you share a recorded video before your PR.

Video ?
Please explain...

**Comment by shounak-dev** [comment]
@Yash-Parsana before your PR, it will be better that you share a recorded video of your updated navigation bar by screen recorder.

**Comment by Yash-Parsana** [comment]
ok no problem
