### ISSUE TITLE
Declaration all static string value to String.xml

### ISSUE THREAD

**Issue by logicgupta** [ByteMonk-GCECT/GCECT-APP#22]
### Contact Details

logicgupta59@gmail.com

### GSSoC-22

yes

### Type of Issue

Others

### Description

I would like to enhance the code by declaration of all the string static value to string.xml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by logicgupta** [comment]
Please assign me this one ...

**Comment by chayan-dev** [comment]
@logicgupta you are assigned 👍also feel free to reach out if you have any doubt

**Comment by logicgupta** [comment]
completed
