### ISSUE TITLE
Implemented Blank Fragment Department of Cersmic

### ISSUE THREAD

**Issue by MohitGupta121** [ByteMonk-GCECT/GCECT-APP#25]
### Contact Details

mohitgupta7780@gmail.com

### GSSoC-22

yes

### Type of Issue

UI Related

### Description

Implemented Blank Fragment Department of Cersmic Technology.

<img src="https://user-images.githubusercontent.com/76530270/156037295-a1b3ca6c-ea9d-4382-bfdf-93076b9b1c5b.png" width="300" height="500">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitGupta121** [comment]
I want to work on this issue, @chayan-dev can you please assign me this.
And please share UI for that also.

**Comment by kunalkayal** [comment]
Hey ! @MohitGupta121,  would you please correct the issue title? It will help us to understand.

**Comment by AgarwalsRahul** [comment]
I would like to work on this issue

**Comment by MohitGupta121** [comment]
@sitamadex11 can u please assign me this issue, as I was created that.

**Comment by HeySitam** [comment]
Yeah sure. But at first please fix the last pr.

**Comment by HeySitam** [comment]
Sure I will assign it to you.

**Comment by MohitGupta121** [comment]
@sitamadex11 Thanks , can u please share figma UI

**Comment by chayan-dev** [comment]
yup, check the figma file already shared

**Comment by MohitGupta121** [comment]
> yup, check the figma file already shared

Okay, same one I'll check.
Thanks you

**Comment by MohitGupta121** [comment]
@chayan-dev Okay bhaiya got it the comment in Figma

**Comment by MohitGupta121** [comment]
@chayan-dev @sitamadex11 can you please review PR #37 for this issue.
