### ISSUE TITLE
UI Update on Home screen Bottom(General Notice Section)

### ISSUE THREAD

**Issue by kunalkayal** [ByteMonk-GCECT/GCECT-APP#29]
## Issue Type:
Update UI and add a suitable color with a glass effect.

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

**Comment by priyanshuborole** [comment]
can I work on this issue? @Kunal-Kayal
