### ISSUE TITLE
No UI for Department of Computer Science and Engg.

### ISSUE THREAD

**Issue by MohitGupta121** [ByteMonk-GCECT/GCECT-APP#33]
## Issue Type:
- [x] UI implementation

## Description:
There is nothing happening while clicking on Department of Computer Science and Engg.
And there is no OnClick and not even any Fragment Implemented for that.

## ScreenShots / Video:
See Nothing Happening in the screen when I click on Department of Computer Science.
https://user-images.githubusercontent.com/76530270/156896082-a8b710a3-b70b-450e-8af1-7303a441f6d3.mp4

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us   know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

I want to Implement this Fragment and set onClick also. Please assign me this issue.

**Comment by MohitGupta121** [comment]
The Computer Science and Engg. Fragment also need to Implemented.
And I want to Implement that.

**Comment by HeySitam** [comment]
First implement the ceramic page. after that you can implement this page too with same ui. but before that we need a discussion. Soon I will give an anouncement regarding meeting.

**Comment by MohitGupta121** [comment]
> First implement the ceramic page. after that you can implement this page too with same ui. but before that we need a discussion. Soon I will give an anouncement regarding meeting.

Okay, That's great I'll implement ceramic first.

**Comment by MohitGupta121** [comment]
@sitamadex11 can you please review my PR #27

**Comment by MohitGupta121** [comment]
@sitamadex11 I raised PR from issue #25 can you now assign me this and review my open PR so that I'll raised PR for that also as this UI is also completed only PR is left.
And can you please merge my contact_us frag PR as that as approved so that new PR not contains the commits and file changed for last PRs

**Comment by MohitGupta121** [comment]
@sitamadex11 can you please assign me this issue 
and can you please review the PR #27

**Comment by cdhiraj40** [comment]
@MohitGupta121 you are assigned! Good luck :)

**Comment by MohitGupta121** [comment]
> 

Thanks you
