### ISSUE TITLE
No UI for Department of Information and Technology 

### ISSUE THREAD

**Issue by MohitGupta121** [ByteMonk-GCECT/GCECT-APP#40]
## Issue Type:
- [x] UI implementation

## Description:
There is nothing happening while clicking on Department of Information and Technology.
And there is no OnClick and not even any Fragment Implemented for that.

## ScreenShots / Video:
See Nothing Happening in the screen when I click on Department of Computer Science.
https://user-images.githubusercontent.com/76530270/156896082-a8b710a3-b70b-450e-8af1-7303a441f6d3.mp4

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us   know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

I want to Implement this Fragment and set onClick also. Please assign me this issue.

**Comment by MohitGupta121** [comment]
@chayan-dev can you please update this UI in figma so that I'll work on this issue

**Comment by HeySitam** [comment]
Mohit for now avoid these issues. Because these all are as same as the ceramic pages. focus on other issues.

**Comment by MohitGupta121** [comment]
> Mohit for now avoid these issues. Because these all are as same as the ceramic pages. focus on other issues.

Okay sure

**Comment by HeySitam** [comment]
you can check recent issues that I am creating

**Comment by MohitGupta121** [comment]
I'm working on notification issue but have some doubt can u please have a voice on discord so that continue on that.

And @sitamadex11 can I'll complete that issue also as I really wants to work on this as to improve my UI skills.
