### ISSUE TITLE
AutoSlider indicator Icon position change in Home page

### ISSUE THREAD

**Issue by HeySitam** [ByteMonk-GCECT/GCECT-APP#41]
## Issue Type:
- [ ] New UI Suggestion
- [ ] Suggestion for existing UI
- [ ] UI implementation
- [x] others

## Description:
On the homepage, the AutoSlider's indicator Icon position should be change. It should be placed at the bottom of the picture.

## ScreenShots / Video:
![auto_slider_pos_change](https://user-images.githubusercontent.com/76570320/158209486-916d6ea9-20ce-41db-94c0-d686739840af.jpg)

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us   know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

**Comment by AgarwalsRahul** [comment]
@sitamadex11 I would like to work on this issue.

**Comment by AgarwalsRahul** [comment]
@sitamadex11 Is it fine?
![Screenshot_20220317-220215](https://user-images.githubusercontent.com/63352614/158848740-2f619b9e-34bf-41a0-8450-0f6be0b45e12.png)

**Comment by HeySitam** [comment]
yeah cool. send the PR. and bro for each issue try to make a new branch on your forked repo.
