### ISSUE TITLE
Nav Drawer edges should be curved

### ISSUE THREAD

**Issue by HeySitam** [ByteMonk-GCECT/GCECT-APP#42]
## Issue Type:
- [ ] New UI Suggestion
- [ ] Suggestion for existing UI
- [ ] UI implementation
- [x] others

## Description:
Nav Drawer edges should be curved

## ScreenShots / Video:
![nav_drawer_edge_curving](https://user-images.githubusercontent.com/76570320/158210903-a5304097-1b24-4e23-a4d5-fbbfe2b07c44.jpg)

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us   know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

**Comment by AgarwalsRahul** [comment]
I would like to work on this issue.

**Comment by HeySitam** [comment]
sure go ahead

**Comment by AgarwalsRahul** [comment]
@sitamadex11 Is it fine?
![Screenshot_20220317-214803](https://user-images.githubusercontent.com/63352614/158847103-43859362-88c7-43e5-8deb-e1d900162dd6.png)

**Comment by HeySitam** [comment]
yeah perfect bro. please fetch the upstream and then send a PR. I will review it.
