### ISSUE TITLE
Notification at the time of downloading

### ISSUE THREAD

**Issue by HeySitam** [ByteMonk-GCECT/GCECT-APP#43]
### GSSoC-22

yes

### Type of Issue

New Feature

### Description

There should be a notification showing the downloading status and after clicking the notification the downloaded file should be open.

As there has many download section so apply it for one section only. later on, I will create a separate issue for that
for now, this is implemented inside the app. but it is needed to show as a notification.
![notification_at_downloading](https://user-images.githubusercontent.com/76570320/158214117-1f2e28ab-56b3-462c-b5de-313d9e87414a.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitGupta121** [comment]
I want to work on this issue, Please assign me this

**Comment by HeySitam** [comment]
sure go ahead.😀

**Comment by HeySitam** [comment]
bro any update?

**Comment by MohitGupta121** [comment]
> bro any update?

Actually I'm waiting for #45 to resolved first so that I'll work on that without any extra file changed.

**Comment by MohitGupta121** [comment]
@sitamadex11 I have to show notification when download is complete ?
