### ISSUE TITLE
Edit Functionality in take note section

### ISSUE THREAD

**Issue by HeySitam** [ByteMonk-GCECT/GCECT-APP#46]
### GSSoC-22

yes

### Type of Issue

New Feature

### Description

on the `Take Note` section there has only delete functionality to delete notes. Also, an edit button is needed to attach below delete button with functionality.

![edit_in_take_note_section](https://user-images.githubusercontent.com/76570320/158220316-9bb8784e-4c37-4896-9e31-5f433b16a3e2.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AgarwalsRahul** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by HeySitam** [comment]
sure

**Comment by HeySitam** [comment]
any update?

**Comment by AgarwalsRahul** [comment]
I'm working on it. busy with some college stuff these days. I will create PR by Sunday.

**Comment by HeySitam** [comment]
No issue bro. Take your time

**Comment by AgarwalsRahul** [comment]
@sitamadex11 is it fine?

https://user-images.githubusercontent.com/63352614/161548694-6bd4fe23-488d-4b66-9604-f762f5bfc6a2.mp4

**Comment by AgarwalsRahul** [comment]
@sitamadex11 verify if it's okay
