### ISSUE TITLE
Administration page UI implementation

### ISSUE THREAD

**Issue by HeySitam** [ByteMonk-GCECT/GCECT-APP#47]
### GSSoC-22

yes

### Type of Issue

UI Related

### Description

Administration page UI should be implemented according to the UI. for now use the dummy data.
@chayan-dev will give you the Figma access.

![administration_page_ui](https://user-images.githubusercontent.com/76570320/158221827-368484ed-a190-47ea-8e8d-0e54615ab47a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vibhuti2002** [comment]
I would like to work on this issue. Please assign me

**Comment by HeySitam** [comment]
sure go ahead

**Comment by Vibhuti2002** [comment]
@sitamadex11 @chayan-dev could you give me Figma access

**Comment by Kunal-Kayal** [comment]
@Vibhuti2002 here is the [figma link:](https://www.figma.com/file/6xXpKNhilvlLJ6HUpC2kkC/University-APP?node-id=0%3A1)   if you haven't got the link yet, otherwise ignore it.

**Comment by chayan-dev** [comment]
@Vibhuti2002 can you give your email so to invite you to figma file for Gssoc

**Comment by Vibhuti2002** [comment]
> @Vibhuti2002 can you give your email so to invite you to figma file for Gssoc

vibhuti2002patil@gmail.com

**Comment by chayan-dev** [comment]
invitation send. 
feel free to reach out if you have any doubt.

**Comment by HeySitam** [comment]
any update @Vibhuti2002 ?

**Comment by Vibhuti2002** [comment]
yeah i am working on the issue

**Comment by HeySitam** [comment]
Great. Take your time

**Comment by Vibhuti2002** [comment]
Should i hard code the list below governing body text or should i use list view

**Comment by HeySitam** [comment]
yeah you can. Just put the text to string.xml
