### ISSUE TITLE
Connected Action bar and Status Bar for immersive experience

### ISSUE THREAD

**Issue by its-me-debk007** [ByteMonk-GCECT/GCECT-APP#56]
## Issue Type:
- [ ] New UI Suggestion
- [x] Suggestion for existing UI
- [ ] UI implementation
- [ ] others

## Description:
The Action bar and Status Bar must be connected for immersive experience

## ScreenShots / Video:
![msg876029335-6868](https://user-images.githubusercontent.com/81604986/161691585-b6c54d1c-82a5-4c24-8abb-eb78b89087d1.jpg)

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us   know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

**Comment by its-me-debk007** [comment]
Please assign me this issue. I'm really interested in it

**Comment by HeySitam** [comment]
sure
go for it.
