### ISSUE TITLE
Text alignment and spacing in Administration Page

### ISSUE THREAD

**Issue by kunalkayal** [ByteMonk-GCECT/GCECT-APP#67]
## Issue Type:
- [ ] New UI Suggestion
- [x] Suggestion for existing UI
- [ ] UI implementation
- [ ] others

## Description:
text alignment and spacing need to be accurate and in right place.

## ScreenShots / Video:
> If you have any UI
![WhatsApp Image 2022-04-16 at 8 30 56 PM](https://user-images.githubusercontent.com/68044529/163683615-ba09e959-9244-43eb-8b6d-cf7debe316c2.jpeg)

## PR Instruction:
        - Issue will be assigned on a first come first serve basis.
        - If you are thinking to make a pr then at first be sure to get assigned.
        - before pushing your PR please make sure to fetch upstream.
        - your pr should be pushed on the `develop` branch only.
        - try to complete your assigned task within specified and if you need more time then please let us   know. 
             - for Level1 : max 3 days
             - for Level2 : max 5 days
             - for Level3 : max 7 day
          As the program has limited time only so please try to complete as fast as you can.
        - With your PR try to send a screenshot or screen recording of your work

**Comment by kunalkayal** [comment]
@sitamadex11 could you please assign it to me so that I can start work as early as possible?

**Comment by AgarwalsRahul** [comment]
@sitamadex11 I would like to work on this issue.

**Comment by HeySitam** [comment]
@AgarwalsRahul bro soon I am creating new issues. Will be happy if you  take one of them.

**Comment by AgarwalsRahul** [comment]
@sitamadex11  Yeah sure

**Comment by Hend123** [comment]
@sitamadex11 please assign to me too issue
