### ISSUE TITLE
Blank Contact Us Fragment

### ISSUE THREAD

**Issue by MohitGupta121** [ByteMonk-GCECT/GCECT-APP#9]
Contact US Fragment is Blank, what we have to add in that Fragment?

<img src="https://user-images.githubusercontent.com/76530270/156037295-a1b3ca6c-ea9d-4382-bfdf-93076b9b1c5b.png" width="300" height="500">

**Comment by MohitGupta121** [comment]
I want to work on that issue, can please someone tell me about what we have to add in that what's the UI for that and what details we have to give in this fragment ? 
**GSSoc-22**

**Comment by Pranjali-49** [comment]
Hey, @MohitGupta121 can you please provide some details about how you want that fragment to be exactly?

**Comment by MohitGupta121** [comment]
@Pranjali-49 I also asking for that, what type the Project Admin want. Like that we have to design.

**Comment by Pranjali-49** [comment]
Okay!

**Comment by shounak-dev** [comment]
![Contact Us Fragment](https://user-images.githubusercontent.com/98251168/156114942-c6b94711-dffe-4390-bd75-d9746a85b7f1.PNG)
Hey, @MohitGupta121 design the Contact Us Fragment like this.

**Comment by HeySitam** [comment]
@MohitGupta121 please try to design like this UI. and try to make the UI responsive not static. If you need any help feel free to ask😁😁

**Comment by MohitGupta121** [comment]
@sitamadex11 Okay I'll make this UI as same as UI with responsive.

Please @sitamadex11  or @Shounak2001 assign me this issue.

As I like to work on that issue and raised that issue.

**Comment by MohitGupta121** [comment]
> 

@Shounak2001  please share little bit clear screenshot as it's not readable

**Comment by chayan-dev** [comment]
![image](https://user-images.githubusercontent.com/50614321/156121280-4981ba5e-a516-4d05-9252-d67234d69fda.png)

ig this will be fine

**Comment by MohitGupta121** [comment]
> ig this will be fine

Yaa, Thanks You @chayan-dev Now Its great.

**Comment by chayan-dev** [comment]
@MohitGupta121 can you give your email so that i can add you to the figma file

**Comment by MohitGupta121** [comment]
Sure @chayan-dev mohitgupta7780@gmail.com

**Comment by Arghaghosh2002** [comment]
Nice Work  @MohitGupta121

**Comment by chayan-dev** [comment]
@MohitGupta121 invitation send. confirm whether you can access it or not

**Comment by MohitGupta121** [comment]
> @MohitGupta121 invitation send. confirm whether you can access it or not

@chayan-dev Got it, Thats you.

**Comment by MohitGupta121** [comment]
@chayan-dev  can u please review my PR #27  , I created same UI as you mentioned.

**Comment by MohitGupta121** [comment]
Can you please now review my PR #27 , as in last PR there are some issues in commit.
Then I create new PR by forking again that repo.
